-- MySQL Script generated by MySQL Workbench
-- Sat Apr 27 19:31:30 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizzeriaGit
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzeriaGit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzeriaGit` DEFAULT CHARACTER SET utf8 COLLATE utf8_danish_ci ;
USE `pizzeriaGit` ;

-- -----------------------------------------------------
-- Table `pizzeriaGit`.`rols`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeriaGit`.`rols` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeriaGit`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeriaGit`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `number_phone` VARCHAR(45) NULL,
  `rol_id` INT NOT NULL,
  `adress_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `rol_users_idx` (`rol_id` ASC) VISIBLE,
  CONSTRAINT `rol_users`
    FOREIGN KEY (`rol_id`)
    REFERENCES `pizzeriaGit`.`rols` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeriaGit`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeriaGit`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeriaGit`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeriaGit`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(10,5) NOT NULL,
  `description` TEXT(100) NOT NULL,
  `category_id` INT NOT NULL,
  `image` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `products_categories_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `products_categories`
    FOREIGN KEY (`category_id`)
    REFERENCES `pizzeriaGit`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeriaGit`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeriaGit`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  `total` DECIMAL(10,5) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `users_orders_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `users_orders`
    FOREIGN KEY (`user_id`)
    REFERENCES `pizzeriaGit`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeriaGit`.`ProductOrders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeriaGit`.`ProductOrders` (
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  INDEX `order_product_idx` (`order_id` ASC) VISIBLE,
  INDEX `product_order_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `order_product`
    FOREIGN KEY (`order_id`)
    REFERENCES `pizzeriaGit`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product_order`
    FOREIGN KEY (`product_id`)
    REFERENCES `pizzeriaGit`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
